# Basic workflow that:
# --> Lints the markdown in the README file and all other Markdown files
# --> Confirms that specific files exist inside of the repository
name: build

# Controls when the action will run.
# Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs
# that can run sequentially or in parallel
jobs:
  # The workflow contains a single job called "build"
  build:
    # Specify that the builds for this repository run on the self-hosted
    # runner currently called "cmpsc102-runner1" and tagged with "self-hosted"
    runs-on: ubuntu-latest
    # The runner will run on the latest version of Ubuntu
    # runs-on: ubuntu-latest
    # Define the steps run in the workflow
    steps:
      # Checkout out the code in the repository
      # Checkout the submodule for the bibliography
      - name: Check out code
        uses: actions/checkout@v2
      # Run the mdl linting tool, which references
      # the .mdlrc file stored in the repo's root
      # for further configuration details
      - name: Run mdl
        uses: actionshub/markdownlint@master
      # Run checks to ensure that files exist in repo
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "README.md,.github/ISSUE_TEMPLATE/assistance_request.md,.github/ISSUE_TEMPLATE/bug_report.md,.github/ISSUE_TEMPLATE/video_request.md"
